ind

diff --git a/.github/workflows/validate-index.yml b/.github/workflows/validate-index.yml
--- a/.github/workflows/validate-index.yml
+++ b/.github/workflows/validate-index.yml
@@ -2,16 +2,15 @@ name: Validate HTML
 on: [push]
 
 jobs: 
-  check-Html:
+  check-html:
     runs-on: ubuntu-latest
     steps: 
       - uses: actions/checkout@v3
       - name: check for index.html
         run: |
-           if [ -f "index.html" ]; then
-             echo "index.html founded"
-           else
-             echo "index.html not found"
-             exit 1
-           fl
-
+          if [ -f "index.html" ]; then
+            echo "index.html found"
+          else
+            echo "index.html not found"
+            exit 1
+          fi
